---
application:
  name: "anota-ai-backend"
  project: "anota-ai-backend"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "mongo-database-anota-ai"
  version: "4.4"
routers:
- name: "main-anota-ai-backend"
  routes:
  - application_name: "anota-ai-backend"
    paths:
    - "/*"
